version: '2'

services:
  app:
    build: .
    container_name: valhalla
    ports:
      - "3000:3000"
      - "8888:8888"
    volumes:
      - .:/var/app/current
    command: sh -c 'npm install && npm start'
